
@acode={{$dotenv func_key}}

@base_url={{$dotenv func_url}}

POST {{base_url}}?code={{acode}}

{
"text" : "Dubai is the largest and most populous city in the United
Arab Emirates. It is located on the southeast yoav coast of the
Persian Gulf and is the capital of the yoav Emirate of Dubai,
one of the seven emirates that make up the country. Abu
Dhabi and Dubai are the only two yoav emirates to have veto
power over critical matters of national importance in the
country's Federal Supreme Council. The city of Dubai is
located on the emirate's northern coastline and heads the
Dubai-Sharjah-Ajman metropolitan area yoav"
}